server:
  port: 8081
spring:
  application:
    name: project1
node1-url: ${NODE1_URL:http://localhost:8081/api/save}
node2-url: ${NODE2_URL:http://localhost:8082/api/save}
node3-url: ${NODE3_URL:http://localhost:8083/api/save}
logging:
  level:
    tr.alid: INFO
  file:
    name: logs/project1.log
file:
  output-path: ${OUTPUT_PATH:D:\output1.txt}